name: pin_code_fields

packages:
  - packages/pin_code_fields
  - packages/pin_code_fields/example
  - packages/pin_code_fields_liquid_glass
  - packages/pin_code_fields_liquid_glass/example
  - packages/showcase

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  test:
    run: melos exec --scope="pin_code_fields" -- flutter test
    description: Run flutter test in pin_code_fields package

  format:
    run: melos exec -- dart format .
    description: Format all packages

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages
